### ISSUE TITLE
Can not find your email address

### ISSUE THREAD

**Issue by bashu** [rwanyoike/dotfiles#1]
Hey,

This repository seems to lack maintenance: https://github.com/rwanyoike/django-addthis, I propose myself as a new maintainer.

If you don't have time for it, nor desire, could you give me the right to push in your repository or just transfer it on my account in github?

Thank you!

**Comment by rwanyoike** [comment]
Hello.

You're right, I no longer maintain the `django-addthis` repository. I am
open to transferring ownership to a new maintainer.

Do you have other open source django projects you currently contribute
to/maintain?

**Comment by bashu** [comment]
Hey,

Glad to hear from you! =)


> On 7 Oct 2020, at 13:18, rwanyoike <notifications@github.com> wrote:
> 
> Hello.
> 
> You're right, I no longer maintain the `django-addthis` repository. I am
> open to transferring ownership to a new maintainer.
> 
> Do you have other open source django projects you currently contribute
> to/maintain?

Yes, I do have them =) For example I maintain (or helping):

https://github.com/shanx/django-maintenancemode <https://github.com/shanx/django-maintenancemode>

https://github.com/adamcharnock/django-tz-detect <https://github.com/adamcharnock/django-tz-detect>

Also I adopted few Django projects and still continue maintaining them, biggest example:

https://github.com/bashu/django-easy-maps <https://github.com/bashu/django-easy-maps>

**Comment by rwanyoike** [comment]
Looks good.

I've requested to @bashu for https://github.com/rwanyoike/django-addthis 👍🏽 

Thank you!

**Comment by bashu** [comment]
@rwanyoike thank you!
